### ISSUE TITLE
screen up to  1024 preview need to adjust

### ISSUE THREAD

**Issue by ArdianR** [didikmulyadi/nodejs-api-doc#1]
![image](https://github.com/didikmulyadi/nodejs-api-doc/assets/18589390/9b4c8eef-6fb8-44aa-bdd1-7555867e7ac0)
![image](https://github.com/didikmulyadi/nodejs-api-doc/assets/18589390/3eff0281-0bc9-49fb-9208-52886a790585)

**Comment by didikmulyadi** [comment]
Hi Fian, thank you for the feedback.

Here is the example result when the screen width <=1024, I will up this in the next release `v1.2.0`
![image](https://github.com/didikmulyadi/nodejs-api-doc/assets/26898125/fe182afd-bb26-4e9a-b93a-ed90e43d68ec)
